### ISSUE TITLE
CIDR Example IP Range should be different

### ISSUE THREAD

**Issue by embano1** [vladimirvivien/go-networking#1]
The `IP Range` in the CIDR example should be

`192.168.100.0 - 192.168.100.255`
instead of
`192.168.100.14 - 192.168.100.255`

Possible fix:
```go
	fmt.Printf("IP Range:       %s - %s\n", ipnet.IP, last)
```

https://github.com/vladimirvivien/go-networking/blob/7e0504e0d323ed34694d8ffd49f1ac53df1a8680/ip/cidr/cidr.go#L55

**Comment by vladimirvivien** [comment]
@embano1 thanks for pointing that out.  I will look into a fix.  Thanks again.
